name: Prettier
on: [push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1

      - run: npm run format
      - run: git status
      # commit any changed files
      # https://github.com/TejaswiNallavolu/angular-app-heroku
      - uses: TejaswiNallavolu/angular-app-heroku@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
